export const CONTROLS = {
  LOOK_LEFT_RIGHT: 1,
  LOOK_UP_DOWN: 2,

  MOVE_FAST: 21,
  MOVE_SLOW: 36,

  MOVE_X: 30,
  MOVE_Y: 31,

  MOVE_DOWN: 152,
  MOVE_UP: 153,

  DECREASE_SPEED: 16,
  INCREASE_SPEED: 17,

  VEHICLE_MOVE_DOWN: 85,
  VEHICLE_MOVE_UP: 86,

  VEHICLE_DECREASE_SPEED: 334,
  VEHICLE_INCREASE_SPEED: 99,
};
